---
title: "TidyTuesday: Housing Prices"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

Analyzing data for #tidytuesday week of 2/5/2019 ([source](https://github.com/rfordatascience/tidytuesday/tree/master/data/2019/2019-02-05))

```{r}
library(tidyverse)
library(RColorBrewer)
library(gganimate)

state_hpi <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-02-05/state_hpi.csv")
mortgage_rates <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-02-05/mortgage.csv")
recession_dates <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-02-05/recessions.csv")
```


### Have mortgage rates increaesd over time?
```{r}
mortgage_rates %>%
  ggplot() +
  geom_line(aes(date, fixed_rate_30_yr))
```

### How does California house price index look like over time?
```{r}
state_hpi %>%
  mutate(diff = price_index - us_avg) %>% 
  #filter(state == 'CA') %>%
  group_by(year, state) %>%
  summarize(us_avg = mean(us_avg),
            price_index = mean(price_index),
            diff_avg = mean(diff)) %>%
  mutate(segment = ifelse(diff_avg > 0, 'above', 'below')) %>%
  ggplot() + 
  geom_col(aes(year, diff_avg, fill = segment)) +
  geom_hline(yintercept = 0, lty = 'dashed') +
  scale_fill_brewer(palette = 'Set1', direction = -1) +
  transition_reveal(year)
```

