---
title: "TidyTuesday: ACS Census Data"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

Analyzing data for #tidytuesday week of 4/30/2018

source: https://github.com/rfordatascience/tidytuesday/tree/master/data/2018-04-30

```{r}
# load packages and parse data
library(tidyverse)
library(scales)
library(RColorBrewer)
library(forecats)
theme_set(theme_bw())

census_raw <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2018-04-30/week5_acs2015_county_data.csv")

census <- census_raw

census
```

Different ways to explore the data but a few possible dimensions: demographics, occupation and socio-economic factors

```{r}
# create tibble for demographic data
census_demo <- 
census %>%
  select(State, TotalPop:Pacific) %>%
  group_by(State) %>%
  summarize_all(funs(sum, mean)) %>% # return the sum & mean for each variable
  select(State, # take the sum for first 3 variables and the mean for everything else
         TotalPop = TotalPop_sum, 
         Men = Men_sum, 
         Women = Women_sum, 
         Hispanic = Hispanic_mean,
         White = White_mean, 
         Black = Black_mean, 
         Native = Native_mean, 
         Asian = Asian_mean, 
         Pacific = Pacific_mean) %>%
  arrange(desc(TotalPop)) %>%
  ungroup()
```

## Where do Asians live in terms of population distribution?
```{r}
census_demo %>%
  top_n(20, Asian) %>%
  ggplot(aes(reorder(State, Asian), Asian/100)) +
  geom_bar(stat='identity', aes(fill=State), alpha=0.8) +
  coord_flip() +
  theme(legend.position='none') +
  xlab("") + 
  ylab("") +
  scale_y_continuous(labels=percent_format())
```

## Where do Asians live in terms of raw count? 
```{r}
census_demo %>%
  select(State, TotalPop, Pct_Asian = Asian) %>%
  mutate(AsianPop = TotalPop * (Pct_Asian/100)) %>%
  top_n(20, AsianPop) %>%
  ggplot(aes(reorder(State, AsianPop), AsianPop)) + 
  geom_bar(stat='identity', aes(fill=State), alpha=0.8) + 
  coord_flip() +
  scale_y_continuous(labels=comma_format()) +
  theme(legend.position='none') +
  xlab("") +
  ylab("")
```

## Distribution of demographics per state
```{r}
census_demo %>%
  select(-TotalPop, -Men, -Women) %>%
  gather(ethnicity, distribution, Hispanic:Pacific) %>%
  mutate_at(vars(ethnicity), as.factor) %>% # converts specific variable from character to factor (not necessary TBH)
  mutate(distribution = distribution / 100) %>%
  ggplot(aes(fct_rev(State), distribution)) + 
  geom_bar(stat='identity', position='stack', aes(fill=ethnicity)) +
  coord_flip() +
  scale_fill_brewer(palette='Spectral') +
  scale_y_continuous(labels=percent_format()) +
  xlab("") +
  ylab("") +
  theme_bw(base_size = 10) 
```



 


